Phrase.create(quote: "Whatever the mind of man can conceive and believe, it can achieve.")
Phrase.create(quote: "I attribute my success to this: I never gave or took any excuse.")
Phrase.create(quote: "The most difficult thing is the decision to act, the rest is merely tenacity.")
Phrase.create(quote: "Definiteness of purpose is the starting point of all achievement. ")
Phrase.create(quote: "We become what we think about.")
Phrase.create(quote: "The most common way people give up their power is by thinking they don’t have any.")
Phrase.create(quote: "The mind is everything. What you think you become.")
Phrase.create(quote: "You can never cross the ocean until you have the courage to lose sight of the shore.")
Phrase.create(quote: "Either you run the day, or the day runs you.")
Phrase.create(quote: "If you hear a voice within you say “you cannot paint,” then by all means paint and that voice will be silenced.")
Phrase.create(quote: "Go confidently in the direction of your dreams.  Live the life you have imagined.")
Phrase.create(quote: "Believe you can and you’re halfway there.")
Phrase.create(quote: "Start where you are. Use what you have.  Do what you can.")
Phrase.create(quote: "Fall seven times and stand up eight.")
Phrase.create(quote: "If the wind will not serve, take to the oars.")
Phrase.create(quote: "You can’t fall if you don’t climb.  But there’s no joy in living your whole life on the ground.")
Phrase.create(quote: "Challenges are what make life interesting and overcoming them is what makes life meaningful.")
Phrase.create(quote: "Limitations live only in our minds.")
Phrase.create(quote: "In order to succeed, your desire for success should be greater than your fear of failure.")
Phrase.create(quote: "There are no traffic jams along the extra mile.")
Phrase.create(quote: "You become what you believe.")
Phrase.create(quote: "I have learned over the years that when one’s mind is made up, this diminishes fear.")
Phrase.create(quote: "It does not matter how slowly you go as long as you do not stop. ")
Phrase.create(quote: "Dream big and dare to fail.")
Phrase.create(quote: "You may be disappointed if you fail, but you are doomed if you don’t try.")
Phrase.create(quote: "The question isn’t who is going to let me; it’s who is going to stop me.")
Phrase.create(quote: "Change your thoughts and you change your world.")
Phrase.create(quote: "Nothing is impossible, the word itself says, “I’m possible!”")
Phrase.create(quote: "If you can dream it, you can achieve it.")
Phrase.create(quote: "You are doing an awesome job!")
Phrase.create(quote: "Keep up the hard work, it will pay off!")
Phrase.create(quote: "If you can't run, walk. If you can't walk, crawl.")
